name: gltf-loader
version: 0.3.0.0
github: sgillespie/haskell-gltf-loader
license: MIT             
author: Sean D Gillespie
maintainer: sean@mistersg.net
copyright: 2022 Sean Gillespie

extra-source-files:
  - README.md
  - data/**/*

synopsis: >-
  High level GlTF loader
category: Graphics
description: >-
  Please see the README on Github at <https://github.com/sgillespie/haskell-gltf-loader#readme>

dependencies:
  - base >= 4.11 && < 10
  - rio >= 0.1.12.0
  - linear
  - microlens
  - microlens-platform

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - OverloadedLists
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

library:
  source-dirs: src
  dependencies:
    - binary
    - bytestring
    - gltf-codec
    - unordered-containers

executables:
  gltf-loader:
    main: Main.hs
    source-dirs: app
    dependencies:
      - gltf-loader
      - microlens-platform
      - optparse-simple

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  gltf-loader-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - base64
      - binary
      - bytestring
      - gltf-loader
      - gltf-codec
      - hspec
      - unordered-containers

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
